
### REQUISIÇÕES PARA USER

GET http://localhost:3001/user/28e0243c-d0e5-48a8-a4f2-152e2e9d24d7
Content-Type: application/json

###

GET http://localhost:3001/user
Content-Type: application/json

###

POST http://localhost:3001/user
Content-Type: application/json

{
    "name": "teste",
    "email": "teste@consultoriafocus.com",
    "password": "1234"
}

###

PATCH  http://localhost:3001/user/af941ab7-1209-4df7-99f5-59bb746184e7
Content-Type: application/json

{}


### REQUISIÇÕES PARA DUTY


GET http://localhost:3001/duty
Content-Type: application/json

###

GET http://localhost:3001/duty/a5f4ffee-ab37-4a94-a264-94bef13d7a7a
Content-Type: application/json

###

POST http://localhost:3001/duty/a5f4ffee-ab37-4a94-a264-94bef13d7a7a
Content-Type: application/json
{}

###

PATCH http://localhost:3001/duty/a5f4ffee-ab37-4a94-a264-94bef13d7a7a
Content-Type: application/json

{}


###Auth

POST http://localhost:3001/auth/sign-in
Content-Type: application/json

{
    "email":"teste@consultoriafocus.com",
    "password":"1234"
}