GET http://localhost:3001/user/1555663d-6ed6-4795-bb03-a9b2d9337503
Content-Type: application/json

###

GET http://localhost:3001/user/
Content-Type: application/json

###

POST http://localhost:3001/user
Content-Type: application/json

{
    "name": "João vitor",
    "email": "joaovitor@consultoriafocus.com",
    "password": "1234"
}